# Generated by Django 3.1.5 on 2021-01-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country Code')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified At')),
            ],
        ),
    ]
