# Generated by Django 3.1.5 on 2021-01-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
